
stripe.apiKey= sk_test_51NJZ0qSEIsGVKIV0pe0kisoA4shmVvHUpmGC6wCc7AhOEyNTQGbDU9R3v3dvaAZBry4rT3w5FGW2iRfWd139hToz00dp5aADZY


spring.datasource.url=jdbc:mysql://localhost:3306/stripe_payments
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
