server.port: 9090

paypal.mode=sandbox
paypal.client.id=AYbhEkkwBjtoSJRtpKx9Rrzl87sKejSXP9QcKzUYehyTVeNkdJ8eni8Td949OLS-5nGNMAVoaY1IRMl-
paypal.client.secret=EMaO2N6ULzSFghUDCde9Pura5ZLt8K9yuAmqM000vz3rAqrr6IBio0IBlZLiXxaW38LISooeamrlYK0R