# SMTP Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prabhatkumarssm72@gmail.com
spring.mail.password=yxwx vbtu esvd mcpd

# TLS Configuration
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


